//Estímulos
var estim_LOWER_BOUND_1 =  "<div class='estim-predic'><p><i>Juan está limpiando su casa. Sus hijos están ayudando a cortar el pasto y ordenar el jardín.</i></p><p>—¿Por qué está limpiando?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_2 =  "<div class='estim-predic'><p><i>El jueves en la oficina Pedro tenía mucho para ordenar.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_3 =  "<div class='estim-predic'><p><i>Esta semana hice una fiesta y la pasé muy bien.</i></p><p>—¿Quiénes fueron a la fiesta?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_4 =  "<div class='estim-predic'><p><i>Juan estaba en su casa descansando y escuchó un ruido fuerte en la calle.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_5 =  "<div class='estim-predic'><p><i>Hablé con Marcos la semana pasada y estaba muy triste.</i></p><p>—¿Qué le pasó?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_6 =  "<div class='estim-predic'><p><i>Me fui de viaje con Mónica por dos semanas.</i></p><p>—¿Llevaron mucho equipaje?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_7 =  "<div class='estim-predic'><p><i>El viernes fuimos a la casa de Pedro a tomar mate.</i></p><p>—¿Hicieron algo más?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_8 =  "<div class='estim-predic'><p><i>Esta semana hay feria judicial y no hay mucho para hacer en la oficina.</i></p><p>—¿Qué hiciste hoy?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_9 =  "<div class='estim-predic'><p><i>Había muchas personas en el estadio y en un momento comenzaron a gritar.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_10 =  "<div class='estim-predic'><p><i>La secretaria estaba leyendo pero tuvo que comenzar a trabajar.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_11 =  "<div class='estim-predic'><p><i>Estoy con poca plata y no puedo salir a cenar hoy.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_12 =  "<div class='estim-predic'><p><i>Después de caminar Pedro paró para desayunar.</i></p><p>—¿Que hizo?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_13 =  "<div class='estim-predic'><p><i>Juana tenía que trabajar el fin de semana y estaba muy cansada.</i></p><p>—¿Qué hizo?</p><p>—  _____________________________ </p></div>";
var estim_LOWER_BOUND_14 =  "<div class='estim-predic'><p><i>Hoy a la tarde lo ví a Marcos en el trabajo y estaba enojado.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_1 =  "<div class='estim-predic'><p><i>Juan está limpiando su departamento. Sus compañeros de la secundaria van a venir de visita a la ciudad.</i></p><p>—¿Por qué está limpiando?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_2 =  "<div class='estim-predic'><p><i>El viernes envié unos regalos a mi familia para navidad.</i></p><p>—¿Llegaron a tiempo?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_3 =  "<div class='estim-predic'><p><i>Esta semana hubo huelga general y hubo una alta adhesión.</i></p><p>—¿Fueron a trabajar en tu oficina?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_4 =  "<div class='estim-predic'><p><i>Marcos fue a Mendoza en las vacaciones y trajo vinos en el micro.</i></p><p>—¿Llegaron bien?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_5 =  "<div class='estim-predic'><p><i>En la inundación se llenó de agua la biblioteca de Carlos.</i></p><p>—¿Perdió muchas cosas?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_6 =  "<div class='estim-predic'><p><i>El auto se rompió y tuvimos que volver caminando.</i></p><p>—¿Qué hicieron con el equipaje?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_7 =  "<div class='estim-predic'><p><i>El viernes había un torneo y el tiempo estaba horrible.</i></p><p>—¿Vieron el torneo?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_8 =  "<div class='estim-predic'><p><i>Ayer nos mudamos al estudio nuevo y hay muchas cosas para acomodar.</i></p><p>—¿Qué hiciste hoy?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_9 =  "<div class='estim-predic'><p><i>La competencia era muy peligrosa y en un momento comenzó una tormenta.</i></p><p>—¿Cómo terminó?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_10 =  "<div class='estim-predic'><p><i>Había paro de transporte pero el médico igualmente atendía.</i></p><p>—¿Fue alguien?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_11 =  "<div class='estim-predic'><p><i>Todavía no cobré y ya vencieron los servicios del departamento.</i></p><p>—¿Cómo resolviste?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_12 =  "<div class='estim-predic'><p><i>Para desayunar Pedro tenía galletitas y bizcochos facturas.</i></p><p>—¿Qué comió?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_13 =  "<div class='estim-predic'><p><i>Juana aprendió a tejer y fue a la feria a vender sus productos.</i></p><p>—¿Vendió mucho?</p><p>—  _____________________________ </p></div>";
var estim_UPPER_BOUND_14 =  "<div class='estim-predic'><p><i>Marcos hizo un pedido por Internet en el exterior y estaba enojado.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
var estim_AHI_1 =  "<div class='estim-predic'><p><i>Jorge desconectó todos los aparatos electrónicos para cambiar de lugar los muebles. Está hablando con Juan, su mejor amigo.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_2 =  "<div class='estim-predic'><p><i>En la oficina, el jefe y los empleados estaban haciendo una reunión y hacía mucho calor.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_3 =  "<div class='estim-predic'><p><i>En la casa, Ana y Pedro, estaban descansando y hacía mucho frío.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_4 =  "<div class='estim-predic'><p><i>En la oficina, el jefe y Marcos estaban en una reunión importante y en el pasillo los empleados estaban haciendo mucho ruido.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_5 =  "<div class='estim-predic'><p><i>Pablo y Marcos estaban descansando en la casa. Era la hora de la siesta y tocaron el timbre.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_6 =  "<div class='estim-predic'><p><i>En la oficina, Ana le quería mostrar un producto en Internet a María.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_7 =  "<div class='estim-predic'><p><i>Juan está en el cine con unos amigos viendo un película y su teléfono comenzó a sonar.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_8 =  "<div class='estim-predic'><p><i>Juan y Marcos se juntaron a ver un partido de fúbol y estaba por empezar.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_9 =  "<div class='estim-predic'><p><i>Ana y Pedro estaban comiendo cuando sonó el teléfono. Pedro estaba esperando una llamada.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_10 =  "<div class='estim-predic'><p><i>Juan estaba viendo la televisión en el living y su hermano estaba en la cocina trabajando.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_11 =  "<div class='estim-predic'><p><i>Marcos tenía un cumpleaños en una quinta y estaba llegando muy tarde.</i></p><p>—  _____________________________ </p></div>";
var estim_AHI_12 =  "<div class='estim-predic'><p><i>Juan está cocinando con María en su pequeña cocina. María quiere sacar algo del horno. </i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_1 =  "<div class='estim-predic'><p><i>Jorge compró una nueva computadora en otro país y quiere encenderla por primera vez. Está hablando con Juan, su mejor amigo.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_2 =  "<div class='estim-predic'><p><i>Dos amigos, Ana y Pablo, estaban en una casa era muy vieja y las cosas estaban llenas de óxido.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_3 =  "<div class='estim-predic'><p><i>Juan estaba con Pablo revisando la calefacción de la casa.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_4 =  "<div class='estim-predic'><p><i>Ana y Julia se despertaron y vieron que con la lluvia se mojaron las maderas de la casa y que estaban hinchadas.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_5 =  "<div class='estim-predic'><p><i>Pablo y Marcos llegaron tarde de la fiesta. Habían perdido la llave y no sabía dónde estaba.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_6 =  "<div class='estim-predic'><p><i>En la oficina estaban sin Internet y Marcos estaba intentando arreglarlo.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_7 =  "<div class='estim-predic'><p><i>El amigo de Juan tiene un virus en el celular y está tildado, no puede usar ninguna aplicación.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_8 =  "<div class='estim-predic'><p><i>Julia y Mara estaban viendo televisión cuando hizo un ruido extraño y se apagó.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_9 =  "<div class='estim-predic'><p><i>Ana y Pedro compraron un televisor nuevo. Todavía no saben muy bien cómo funciona.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_10 =  "<div class='estim-predic'><p><i>Juan estuvo todo el día trabajando y cuando volvió a su casa estaba muy cansado.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_11 =  "<div class='estim-predic'><p><i>A María le andaba mal el auto y su hermano tenía un cumpleaños.</i></p><p>—  _____________________________ </p></div>";
var estim_LITERAL_12 =  "<div class='estim-predic'><p><i>Juan se lastimó el codo jugando al fútbol. Está en una consulta con el médico.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_1 =  "<div class='estim-predic'><p><i>El martes teníamos una reunión en la oficina y había muchos problemas con el tránsito.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_2 =  "<div class='estim-predic'><p><i>Analía tiene una fiesta el fin de semana. Va a comprarse un vestido y unos zapatos.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_3 =  "<div class='estim-predic'><p><i>Marta y Pedro están en el supermercado. A la noche tienen una fiesta con 10 personas.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_4 =  "<div class='estim-predic'><p><i>La semana pasada fuimos a ver un concierto de rock.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_5 =  "<div class='estim-predic'><p><i>Ayer compré un aire acondicionado y mañana vienen a instalarlo.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_6 =  "<div class='estim-predic'><p><i>En la feria de artesanías había cosas muy lindas.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_7 =  "<div class='estim-predic'><p><i>En el viaje hicimos una escala para cambiar de avión.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_8 =  "<div class='estim-predic'><p><i>Visité una muestra de arte el otro día.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_9 =  "<div class='estim-predic'><p><i>El jueves fuimos a una fiesta del trabajo.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_10 =  "<div class='estim-predic'><p><i>El sábado me llamó por teléfono Juan muy emocionado.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_11 =  "<div class='estim-predic'><p><i>Ana necesitaba enviar un telegrama para el trabajo y no sabía cómo hacer.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_12 =  "<div class='estim-predic'><p><i>Juan fue de visita por primera vez a la capital del país.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_13 =  "<div class='estim-predic'><p><i>Mañana viene el arquitecto a supervisar la obra.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_14 =  "<div class='estim-predic'><p><i>El empleado tenia que ir al banco porque necesitaba hacer un depósito.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_15 =  "<div class='estim-predic'><p><i>Marcos estaba en el shopping haciendo compras para Navidad.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_16 =  "<div class='estim-predic'><p><i>Ayer tuve un partido de fútbol con mis compañeros del trabajo.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_17 =  "<div class='estim-predic'><p><i>Había muchas personas en la plaza y un había un recital.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_18 =  "<div class='estim-predic'><p><i>La maestra estaba leyendo pero tuvo que salir al patio.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_19 =  "<div class='estim-predic'><p><i>Tengo un problema y no puedo ir al cine hoy.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_PREGUNTA_20 =  "<div class='estim-predic'><p><i>Me llamó el mecánico y me pasó el precio de la reparación del auto.</i></p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_1 =  "<div class='estim-predic'><p><i>Marcos va a remodelar su casa y está viendo de dónde va a sacar el dinero.</i></p><p>—¿De dónde vas a sacar la plata?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_2 =  "<div class='estim-predic'><p><i>Este fin de semana voy a ir al campo de mis tíos. Voy a ir con mis amigos del gimnasio.</i></p><p>—¿Qué van a hacer?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_3 =  "<div class='estim-predic'><p><i>Estuve trabajando toda la semana y estoy muy cansado.</i></p><p>—¿Vas a hacer algo el fin de semana?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_4 =  "<div class='estim-predic'><p><i>Me mudé el fin de semana y tengo muchas cosas desordenadas.</i></p><p>—¿Querés que te dé una mano?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_5 =  "<div class='estim-predic'><p><i>En la tormenta se inundó el barrio.</i></p><p>—¿Entró agua a tu casa?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_6 =  "<div class='estim-predic'><p><i>María va a cocinar una torta.</i></p><p>—¿Compraste los ingredientes?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_7 =  "<div class='estim-predic'><p><i>Ana compró una tele nueva y todavía no la probó.</i></p><p>—¿Ya probaste la tele nueva?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_8 =  "<div class='estim-predic'><p><i>En la oficina hubo un corte de luz y no podíamos trabajar.</i></p><p>—¿Qué hicieron?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_9 =  "<div class='estim-predic'><p><i>El otro día me asaltaron y me robaron el celular.</i></p><p>—¿Te lastimaron?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_10 =  "<div class='estim-predic'><p><i>El fin de semana hubo un partido de fútbol. Pedro no vio el partido.</i></p><p>—¿Viste el partido?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_11 =  "<div class='estim-predic'><p><i>El martes en la oficina estaban todos muy tristes.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_12 =  "<div class='estim-predic'><p><i>El viernes fui a jugar un partido de fútbol con mis amigos. Terminé muy tarde.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_13 =  "<div class='estim-predic'><p><i>Esta semana es el cumpleaños de mi papá y todavía no le compré un regalo.</i></p><p>—¿Cuándo vas a ir?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_14 =  "<div class='estim-predic'><p><i>En el trabajo había empleados nuevos. Juan no los conoce muy bien.</i></p><p>—¿Hace mucho que trabajás acá?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_15 =  "<div class='estim-predic'><p><i>La próxima semana Marta tiene un casamiento. No sabe qué ponerse.</i></p><p>—¿Te vas a comprar un vestido?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_16 =  "<div class='estim-predic'><p><i>Ayer hubo huelga en la fábrica.</i></p><p>—¿Fuiste a trabajar?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_17 =  "<div class='estim-predic'><p><i>Juan estuvo trabajando toda la mañana y ahora tiene hambre.</i></p><p>—¿Qué vas a comer?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_18 =  "<div class='estim-predic'><p><i>Esta tarde corrí en la plaza.</i></p><p>—¿Te fue bien?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_19 =  "<div class='estim-predic'><p><i>El subte estaba lleno y subió una señora con un bebé.</i></p><p>—¿Quiere sentarse señora?</p><p>—  _____________________________ </p></div>";
var estim_CONTROL_RESPUESTA_20 =  "<div class='estim-predic'><p><i>El Martes Marta tenía mucho para limpiar.</i></p><p>—¿Qué pasó?</p><p>—  _____________________________ </p></div>";
